# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4a6e8875b92799b2e1f1ebe8b06f93367acf64b58a93704f276bdaf8cd042cae453075cef18ae3ede7cddfd940638d0fee7f720dd966ffef3e48a62888c6457

test:
  secret_key_base: 9899bba28e2bf69b4edc81ae678dee671c35b1b0a58e1b0c4717d71f74b3c4b5d096bf44f6eac15063d784b477984ad2cfdc8f426b85d243104479489a2c1314

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
